### ISSUE TITLE
No sound at all

### ISSUE THREAD

**Issue by HerveF2** [krzysk1/bgear#2]

**Comment by krzysk1** [comment]
I'm not sure if we can to add licensed files in our public releases.  You have to copy manually all tsb files from extra300

see installation steps:

1. Unzip file and move the folder "bgear" to C:\Users~\Documents\Aerofly FS2\aircraft.
2. Copy all *.tsb files from "extra300" folder from your Aerofly FS2 installation path into "bgear" folder.

(Maybe I need to search for free alternative)
