### ISSUE TITLE
No Engine sound at all

### ISSUE THREAD

**Issue by HerveF2** [krzysk1/bgear#3]
Hi, superb model, but in my AF2, the Bgear has no engine sound at all !

**Comment by krzysk1** [comment]
I'm not sure if we can to add licensed files in our public releases. You have to copy manually all tsb files from extra300

see installation steps:

Unzip file and move the folder "bgear" to C:\Users~\Documents\Aerofly FS2\aircraft.
Copy all *.tsb files from "extra300" folder from your Aerofly FS2 installation path into "bgear" folder.
(Maybe I need to search for free alternative)

**Comment by krzysk1** [comment]
For Aerofly FS4  version  copy all *.tsb files from "extra300" folder from your Aerofly FS4 installation path into "bgear\sounds" folder.
